name: ring_shop_list
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  connectivity_plus: ^1.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.0
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  http: ^0.13.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  freezed: ^0.14.2
  json_serializable: ^6.1.5
  # mockito: ^5.0.7
  mocktail: ^0.2.0
  very_good_analysis: ^2.1.1

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 200
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 300
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 800
